from sqlalchemy import Column, Integer, String,Text,Float,SmallInteger,DateTime
from db import Base
class Company(Base):
    __tablename__ = "tb_company"

    id = Column(Integer, primary_key=True, autoincrement=True, comment='ID')
    company_name = Column(String(128), nullable=True, comment='主体名称')
    company_code = Column(String(64), nullable=True, comment='注册号')
    credit_code = Column(String(64), nullable=False, default='', comment='统一社会信用代码')
    company_address = Column(String(500), nullable=True, comment='地址')
    authority = Column(String(100), nullable=True, comment='登记机关')
    business_scope = Column(Text, nullable=True, comment='经营范围')
    capital = Column(String(128), nullable=True, comment='注册资本')
    capital_unit = Column(String(128), nullable=False, default='万人民币', comment='注册资本单位')
    capital_value = Column(Float, nullable=False, default=0, comment='注册资本数值')
    capital_value_rmb = Column(Float, nullable=False, default=0, comment='注册资本人民币值')
    company_status = Column(Integer, nullable=True, default=0, comment='主体状态')
    company_status_name = Column(String(64), nullable=True, comment='主体状态名称')
    company_type = Column(String(64), nullable=True, comment='主体类型')
    company_type_id = Column(Integer, nullable=False, default=0, comment='企业下面分类id')
    personal_flag = Column(SmallInteger, nullable=False, default=0, comment='个人标识')
    establish_date = Column(String(64), nullable=True, comment='有效期')
    legal_person = Column(String(64), nullable=True, comment='法人')
    operation_start_date = Column(String(64), nullable=True, comment='起始时间')
    operation_end_date = Column(String(64), nullable=True, comment='结束时间')
    data_source = Column(SmallInteger, nullable=False, default=1, comment='数据来源')
    remark = Column(Text, nullable=True, comment='备注信息')
    industry = Column(String(64), nullable=True, comment='所属行业')
    industry_id = Column(Integer, nullable=False, default=0, comment='行业id')
    link_man = Column(String(64), nullable=True, comment='联系人')
    link_phone = Column(String(64), nullable=True, comment='联系电话')
    link_email = Column(String(64), nullable=True, comment='联系邮箱')
    area_id = Column(Integer, nullable=False, default=0, comment='所属地区id')
    user_id = Column(Integer, nullable=True, comment='操作人')
    trade_flag = Column(SmallInteger, nullable=False, default=0, comment='交易标识')
    is_online = Column(SmallInteger, nullable=False, default=0, comment='是否在网')
    company_id_old = Column(Integer, nullable=True, comment='旧company_id')
    company_tel = Column(String(100), nullable=True, comment='公司电话')
    current_loc = Column(String(255), nullable=True, comment='当前地址')
    order_index = Column(Integer, nullable=False, default=3, comment='排序')
    province = Column(String(100), nullable=True, comment='省')
    province_id = Column(Integer, nullable=False, default=0, comment='省机构id')
    city = Column(String(100), nullable=True, comment='市')
    city_id = Column(Integer, nullable=False, default=0, comment='市机构id')
    county = Column(String(100), nullable=True, comment='区')
    county_id = Column(Integer, nullable=False, default=0, comment='区机构id')
    street = Column(String(100), nullable=True, comment='街道')
    street_id = Column(Integer, nullable=False, default=0, comment='街道id')
    road = Column(String(255), nullable=True, comment='道路名称')
    road_id = Column(Integer, nullable=False, default=0, comment='道路id')
    created_at = Column(DateTime, nullable=True, comment='创建时间')
    updated_at = Column(DateTime, nullable=True, comment='更新时间')
    deleted_at = Column(DateTime, nullable=True, comment='删除时间')
    lat = Column(String(32), nullable=True, comment='纬度')
    lng = Column(String(32), nullable=True, comment='经度')
    back_flag = Column(SmallInteger, nullable=False, default=0, comment='退回标识')
    unusual_flag = Column(SmallInteger, nullable=False, default=1, comment='退回状态')
    dead_flag = Column(SmallInteger, nullable=False, default=1, comment='退回状态')
    label_names = Column(String(500), nullable=True, comment='标签名称')
    collect_flag = Column(SmallInteger, nullable=False, default=0, comment='收藏标识')
    patrol_time = Column(DateTime, nullable=True, comment='巡查时间')
    patrol_num = Column(Integer, nullable=False, default=0, comment='巡查次数')
    judge_num = Column(Integer, nullable=False, default=0, comment='判定次数')
    judge_time = Column(DateTime, nullable=True, comment='判定时间')
    attention_flag = Column(SmallInteger, nullable=False, default=0, comment='是否关注')
    company_pripid = Column(String(100), nullable=True)
    part_business_scope = Column(Text, nullable=True)
    check_date = Column(DateTime, nullable=True)
    administer_unit = Column(String(50), nullable=True)
    legal_idcard = Column(String(50), nullable=True)
    legal_mobile = Column(Integer, nullable=True)
    employed_num = Column(Integer, nullable=False, default=0)
    flexible_employ_flag = Column(SmallInteger, nullable=False, default=0, comment='灵活用工企业标识')
    business_address = Column(Text, nullable=True, comment='经营场所')
    actual_business_address = Column(Text, nullable=True, comment='实际经营地址')
    compare_flag = Column(SmallInteger, nullable=False, default=0, comment='比对标示')
    regorg = Column(Integer, nullable=False, default=0, comment='登记机关')
    localadm = Column(Integer, nullable=False, default=0, comment='管辖单位')
    currency = Column(Integer, nullable=False, default=0, comment='单位')
    enttype = Column(Integer, nullable=False, default=0, comment='企业类型')
    industryphy = Column(String(100), nullable=True, default='0', comment='行业编号')
    ptbusscope = Column(Text, nullable=True, comment='子经营范围')
    hzrq = Column(DateTime, nullable=True, comment='核准日期')
    cerno = Column(String(50), nullable=True, comment='身份证')
    history_name = Column(String(128), nullable=True, comment='主体名称')
    check_flag = Column(SmallInteger, nullable=False, default=0, comment='小程序核查状态')
    org_name = Column(String(100), nullable=True, comment='管辖单位名称')
    localadm_sj = Column(Integer, nullable=False, default=0, comment='上级管辖单位编号')
    industry_ids = Column(Integer, nullable=False, default=0, comment='行业编号')
    company_uuid = Column(String(200), nullable=True, comment='企业唯一标识')
    sync_flag = Column(SmallInteger, nullable=False, default=0, comment='数据同步状态')
    website_flag = Column(SmallInteger, nullable=False, default=0, comment='交易网站标识')
    shop_flag = Column(SmallInteger, nullable=False, default=0, comment='网店标识')
    platform_flag = Column(SmallInteger, nullable=False, default=0, comment='平台标识')
    takeout_flag = Column(SmallInteger, nullable=False, default=0, comment='本地生活标识')
    app_flag = Column(SmallInteger, nullable=False, default=0, comment='APP标识')
    wechat_app_flag = Column(SmallInteger, nullable=False, default=0, comment='小程序标识')
    wechat_official_flag = Column(SmallInteger, nullable=False, default=0, comment='公众号标识')
    carrier_num = Column(SmallInteger, nullable=False, default=0, comment='载体类型数量')
    label_num = Column(SmallInteger, nullable=False, default=0, comment='标签数量')
    risk_level = Column(String(1), nullable=True, comment='风险等级')
    credit_level = Column(String(1), nullable=True, comment='信用等级')
    xzxk = Column(SmallInteger, nullable=False, default=0, comment='行政许可')
    flss = Column(SmallInteger, nullable=False, default=0, comment='法律诉讼')
    xzcf = Column(SmallInteger, nullable=False, default=0, comment='行政处罚')
    zscq = Column(SmallInteger, nullable=False, default=0, comment='知识产权')
    tsjb = Column(SmallInteger, nullable=False, default=0, comment='投诉举报')
    abnormal_num = Column(Integer, nullable=False, default=0, comment='异常数据数量')
    rand_num = Column(Integer, nullable=False, default=0, comment='随机数量')
    check_time = Column(DateTime, nullable=True, comment='检查时间')
    official_website = Column(String(255), nullable=True, comment='官网')
    credit_score = Column(Integer, nullable=False, default=0, comment='信用得分')
    risk_score = Column(Integer, nullable=False, default=0, comment='风险得分')
    live_flag = Column(SmallInteger, nullable=False, default=0, comment='主播标识')
    user_flag = Column(SmallInteger, nullable=False, default=0, comment='平台用户标识')
    labels_industry_name = Column(String(255), nullable=True, default='', comment='产业标签')
    labels_industry_id = Column(String(255), nullable=True, default='', comment='产业标签id')
    warn_flag = Column(SmallInteger, nullable=False, default=0, comment='风险标识')
    industry_id_match = Column(Integer, nullable=False, default=0, comment='关联行业id')
    industry_id_level=Column(SmallInteger, nullable=False, default=0, comment='关联行业层级')










