from sqlalchemy import Column, Integer, String, Float, Text, TIMESTAMP, SmallInteger,DateTime
from db import Base
from datetime import datetime

class Shop(Base):
    __tablename__ = 'tb_shop'

    id = Column(Integer, primary_key=True, autoincrement=True)
    platform_name = Column(String(128), nullable=True, comment='平台名称')
    shop_id = Column(String(128), nullable=True, comment='店铺平台ID')
    seller_id = Column(String(64), default='0', comment='卖家id,只有淘宝和天猫有，为了判断死活')
    shop_name = Column(String(500), nullable=True, comment='网店名称')
    shop_url = Column(String(1024), nullable=False, comment='店铺链接')
    shop_logo = Column(String(255), nullable=True, comment='店铺logo图片地址')
    link_man = Column(String(128), nullable=True, comment='店铺联系人名称')
    link_phone = Column(String(64), nullable=True, comment='联系电话')
    shop_type_id = Column(SmallInteger, default=0, nullable=False, comment='店铺分类')
    shop_type_name = Column(String(100), nullable=True, comment='店铺归一类型')
    shop_cate = Column(String(128), nullable=True, comment='店铺类别名称')
    shop_address = Column(String(255), nullable=True, comment='店铺地址')
    province = Column(String(64), nullable=True, comment='省份')
    province_id = Column(Integer, default=0, nullable=False, comment='省机构id')
    city = Column(String(64), nullable=True, comment='城市')
    city_id = Column(Integer, default=0, nullable=False, comment='市机构id')
    county = Column(String(128), nullable=True, comment='区县')
    county_id = Column(Integer, default=0, nullable=False, comment='区机构id')
    platform_id = Column(Integer, default=0, nullable=True, comment='平台ID')
    area_id = Column(Integer, default=0, nullable=False, comment='区域id')
    street_id = Column(Integer, default=0, nullable=False, comment='所属街道id')
    road_id = Column(Integer, default=0, nullable=False)
    month_total_sold = Column(String(255), default='0', nullable=True, comment='月销量')
    delivery_location = Column(String(100), nullable=True, comment='发货地')
    describe_score = Column(String(255), nullable=True, comment='描述评分')
    describe_compare = Column(String(32), nullable=True, comment='描述对比')
    service_score = Column(String(255), nullable=True, comment='服务评分')
    service_compare = Column(String(32), nullable=True, comment='服务对比')
    logistics_score = Column(String(255), nullable=True, comment='物流评分')
    logistics_compare = Column(String(255), nullable=True, comment='物流对比')
    goods_count = Column(Integer, default=0, nullable=False, comment='店铺商品数量')
    shop_score = Column(String(255), nullable=True, comment='店铺评分')
    shop_create_time = Column(String(255), nullable=True, comment='店铺创建时间')
    dead_time = Column(String(64), nullable=True, comment='店铺死链时间')
    fans_count = Column(String(100), default='0', nullable=True, comment='粉丝数量')
    company_id = Column(Integer, default=0, nullable=False, comment='主体表外键')
    industry_id = Column(Integer, default=0, nullable=False, comment='行业id')
    capital_value = Column(Float, default=0, nullable=False, comment='注册资金额度')
    company_name = Column(String(255), nullable=True, comment='主体名称')
    credit_code = Column(String(100), nullable=True)
    remark = Column(Text, nullable=True, comment='备注')
    patrol_num = Column(SmallInteger, default=0, nullable=False, comment='巡查次数')
    data_source = Column(SmallInteger, default=1, nullable=False, comment='数据来源 1：系统 2：手动创建 3:机构')
    patrol_time = Column(TIMESTAMP, nullable=True, comment='巡查最近时间')
    order_index = Column(Integer, default=3, nullable=False, comment='排序')
    created_at = Column(DateTime, default=datetime.utcnow)  # 默认当前时间
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)  # 默认当前时间，更新时自动更新
    deleted_at = Column(TIMESTAMP, nullable=True, comment='删除时间')  # 新增字段
    user_id = Column(Integer, default=0, nullable=False, comment='创建人id')
    company_id_old = Column(Integer, nullable=True, comment='主库company_id')
    judge_num = Column(SmallInteger, default=0, nullable=False, comment='巡查次数')
    judge_time = Column(TIMESTAMP, nullable=True, comment='巡查最近时间')
    dead_flag = Column(SmallInteger, default=1, nullable=False, comment='1：正常  2：异常')
    shop_flag = Column(SmallInteger, default=1, nullable=False, comment='1:本地的  2：全国性')
    label_names = Column(String(500), default='', nullable=False, comment='标签名称')
    personal_flag = Column(SmallInteger, default=0, nullable=False, comment='是否是个人 ：0 ：企业 1：个人')
    company_personal_flag = Column(SmallInteger, default=0, nullable=False,
                                   comment='主体类型标识0：全部  1：公司  2:个体工商户 3：个人')
    unusual_flag = Column(SmallInteger, default=1, nullable=False, comment='1：正常  2：异常')
    collect_flag = Column(SmallInteger, default=0, nullable=False, comment='1：收藏')
    licence_flag = Column(SmallInteger, default=0, nullable=False, comment='亮照标识0:待查看1：已亮2：未亮')
    business_volume = Column(Integer, default=0, nullable=False, comment='年度交易额')
    licence_img = Column(Text, nullable=True, comment='亮照图片')
    ip_address = Column(String(50), nullable=True, comment='ip地址')
    business_licence_url = Column(Text, nullable=True, comment='营业执照url')
    business_licence_img = Column(String(500), nullable=True, comment='营业执照图片url')
    declare_msg = Column(String(500), nullable=True, comment='自我声明信息')
    duty = Column(String(100), nullable=True, comment='职务')
    business_type = Column(SmallInteger, default=1, nullable=False, comment='电子商务类型')
    home_server_address = Column(String(500), nullable=True, comment='国内服务器物理位置')
    foreign_server_address = Column(String(500), nullable=True, comment='国外服务器物理位置')
    quality_score = Column(Float, default=0, nullable=False, comment='质量评分')
    negative_comment_num = Column(Integer, default=0, nullable=False, comment='差评数')
    single_negative_comment_highrate = Column(String(100), default='', nullable=False, comment='单一商品最高差评率')
    comment_num = Column(Integer, default=0, nullable=False, comment='总评评数')
    industry_label_names = Column(String(500), default='', nullable=True, comment='产业标签')
    float_flag = Column(SmallInteger, default=1, nullable=False, comment='1：升   2：降')
    shop_type_ff = Column(String(255), nullable=True, comment='分发抓取店铺类型名称')
    legal_person = Column(String(255), nullable=True, comment='法人')
    certificate_show_flag = Column(SmallInteger, default=0, nullable=False, comment='亮证标识 0 待查看 1 已亮 2未亮')
    certificate_show_type = Column(String(255), nullable=True, comment='亮证类型')
    promise_show_flag = Column(SmallInteger, default=0, nullable=False, comment='0 待查看 1 已亮 2 未亮')
    company_uuid = Column(String(255), nullable=True, comment='主体唯一标识')
    authority = Column(Text, nullable=True, comment='经营范围')
    business_scope = Column(Text, nullable=True, comment='经营范围')
    shop_lat = Column(String(100), nullable=True, comment='店铺经度')
    shop_lng = Column(String(100), nullable=True, comment='店铺纬度')
    match_flag = Column(Integer, default=0, nullable=False, comment='匹配标识')
    service_tags = Column(String(255), nullable=True, comment='店铺服务标识')
    trade_flag = Column(Integer, nullable=True, comment='交易标识')
    dead_check_flag = Column(SmallInteger, default=0, nullable=False, comment='死链扫描标识0：默认 1：扫描过')
    collection_flag = Column(SmallInteger, default=0, nullable=False, comment='0 普通店铺  1 集合店铺')
    shop_uuid = Column(String(100), default='', nullable=True)
    open_year = Column(SmallInteger, default=0, nullable=False, comment='开店年长')
    labels_industry_name = Column(String(255), default='', nullable=True)
    is_dead = Column(SmallInteger, default=0, nullable=False, comment='主库的死活标识')
    open_time = Column(String(64), nullable=True, comment='产业标签名称 已英文逗号分割')
    labels_industry_id = Column(String(255), default='', nullable=True)
    goods_static_status = Column(SmallInteger, default=0, nullable=False, comment='商品数统计状态')
    judge_content = Column(Text, nullable=True, comment='日常巡查数据')
    judge_content_flag = Column(SmallInteger, default=0, nullable=False, comment='是否更新了judge_content_flag')
    filing_status = Column(SmallInteger, default=1, nullable=False, comment='实地核查状态')
    field_check_user_id = Column(Integer, default=0, nullable=False, comment='实地核查人id')
    field_check_time = Column(TIMESTAMP, nullable=True, comment='实地核查时间')
    data_field_check_id = Column(Integer, default=0, nullable=False, comment='实地核查id')
    xinsi_flag = Column(SmallInteger, default=0, nullable=False, comment='主库是否存在标识')
    light_flag = Column(Integer, default=1000, nullable=True, comment='亮照标识')
    judge_content_num = Column(Integer, default=0, nullable=False, comment='系统自动巡查次数')
    month_total_sold_num = Column(Integer, nullable=True, comment='月销量数量')
    share_code = Column(String(500), nullable=True, comment='二维码图片')
    illegal_flag = Column(SmallInteger, default=-1, nullable=True, comment='巡查类型')
    judge_id = Column(Integer, default=0, nullable=False)
    live_user_id = Column(Integer, nullable=True, comment='直播间id')
