from sqlalchemy import Column, Integer, String, Float, Text, TIMESTAMP, SmallInteger,DateTime
from db import Base
from datetime import datetime

class Shop(Base):
    __tablename__ = 'tb_shop'
    __table_args__ = {'comment': '店铺表'}
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    platform_name = Column(String(128), comment='平台名称')
    shop_id = Column(String(128), comment='店铺平台ID')
    seller_id = Column(String(64), comment='卖家id,只有淘宝和天猫有，为了判断死活')
    shop_name = Column(String(255), comment='网店名称')
    shop_url = Column(String(1000), nullable=False, comment='店铺链接')
    shop_logo = Column(String(255), comment='店铺logo图片地址')
    link_man = Column(String(128), comment='店铺联系人名称')
    link_phone = Column(String(64), comment='联系电话')
    shop_type_id = Column(SmallInteger, nullable=False, server_default='0', comment='店铺分类')
    shop_type_name = Column(String(100), comment='店铺归一类型')
    shop_cate = Column(String(128), comment='店铺类别名称')
    shop_address = Column(String(255), comment='店铺地址')
    province = Column(String(128), comment='省份')
    province_id = Column(Integer, nullable=False, server_default='0', comment='省机构id')
    city = Column(String(128), comment='城市')
    city_id = Column(Integer, nullable=False, server_default='0', comment='市机构id')
    county = Column(String(128), comment='区县')
    county_id = Column(Integer, nullable=False, server_default='0', comment='区机构id')
    platform_id = Column(Integer, comment='平台ID')
    area_id = Column(Integer, nullable=False, server_default='0', comment='区域id')
    street_id = Column(Integer, nullable=False, server_default='0', comment='所属街道id')
    month_total_sold = Column(String(255), server_default='0', comment='月销量')
    delivery_location = Column(String(100), comment='发货地')
    describe_score = Column(String(255), comment='描述评分')
    describe_compare = Column(String(255), comment='描述对比')
    service_score = Column(String(255), comment='服务评分')
    service_compare = Column(String(255), comment='服务对比')
    logistics_score = Column(String(255), comment='物流评分')
    logistics_compare = Column(String(255), comment='物流对比')
    goods_count = Column(Integer, nullable=False, server_default='0', comment='店铺商品数量')
    shop_score = Column(String(255), comment='店铺评分')
    shop_create_time = Column(String(255), comment='店铺创建时间')
    dead_time = Column(DateTime, comment='店铺死链时间')
    fans_count = Column(String(100), server_default='0', comment='粉丝数量')
    company_id = Column(Integer, nullable=False, server_default='0', comment='主体表外键')
    industry_id = Column(Integer, nullable=False, server_default='0', comment='行业id')
    capital_value = Column(Float, nullable=False, server_default='0', comment='注册资金额度')
    company_name = Column(String(255), comment='主体名称')
    credit_code = Column(String(100))
    company_address = Column(String(255))
    org_name = Column(String(255))
    remark = Column(Text, comment='备注')
    patrol_num = Column(SmallInteger, nullable=False, server_default='0', comment='巡查次数')
    data_source = Column(SmallInteger, nullable=False, server_default='1', comment='数据来源 1：系统 2：手动创建 3:机构 4:新维')
    patrol_time = Column(TIMESTAMP, comment='巡查最近时间')
    order_index = Column(Integer, nullable=False, server_default='3', comment='排序')
    created_at = Column(TIMESTAMP, comment='创建时间')
    updated_at = Column(TIMESTAMP, comment='修改时间')
    deleted_at = Column(TIMESTAMP, comment='删除时间')
    user_id = Column(Integer, nullable=False, server_default='0', comment='创建人id')
    company_id_old = Column(Integer, comment='主库company_id')
    judge_num = Column(SmallInteger, nullable=False, server_default='0', comment='巡查次数')
    judge_time = Column(TIMESTAMP, comment='巡查最近时间')
    dead_flag = Column(SmallInteger, nullable=False, server_default='1', comment='1：正常  2：异常')
    shop_flag = Column(SmallInteger, nullable=False, server_default='1', comment='1:本地的  2：全国性')
    label_names = Column(String(500), nullable=False, server_default='', comment='标签名称')
    personal_flag = Column(SmallInteger, nullable=False, server_default='0', comment='是否是个人 ：0 ：企业 1：个人')
    unusual_flag = Column(SmallInteger, nullable=False, server_default='1', comment='1：正常  2：异常')
    collect_flag = Column(SmallInteger, nullable=False, server_default='0', comment='1：收藏')
    licence_flag = Column(SmallInteger, nullable=False, server_default='0', comment='亮照标识')
    business_volume = Column(Integer, nullable=False, server_default='0', comment='年度交易额')
    licence_img = Column(Text, comment='亮照图片')
    ip_address = Column(String(50), comment='ip地址')
    business_licence_url = Column(Text, comment='营业执照url，第三方原始地址')
    business_licence_img = Column(String(500), comment='营业执照图片url，(自己的文件路径地址)')
    declare_msg = Column(String(500), comment='自我声明信息')
    duty = Column(String(100), comment='职务')
    business_type = Column(SmallInteger, nullable=False, server_default='1', comment='电子商务类型')
    home_server_address = Column(String(500), comment='国内服务器物理位置')
    foreign_server_address = Column(String(500), comment='国外服务器物理位置')
    quality_score = Column(Float, nullable=False, server_default='0', comment='质量评分')
    negative_comment_num = Column(Integer, nullable=False, server_default='0', comment='差评数')
    single_negative_comment_highrate = Column(String(100), nullable=False, server_default='', comment='单一商品最高差评率')
    comment_num = Column(Integer, nullable=False, server_default='0', comment='总评评数')
    industry_label_names = Column(String(500), server_default='', comment='产业标签')
    float_flag = Column(SmallInteger, nullable=False, server_default='1', comment='1：升   2：降')
    shop_type_ff = Column(String(255), comment='分发抓取店铺类型名称')
    legal_person = Column(String(255), comment='法人')
    certificate_show_flag = Column(SmallInteger, nullable=False, server_default='0', comment='亮证标识 0 待查看 1 已亮 2未亮')
    certificate_show_type = Column(String(255), comment='亮证类型')
    promise_show_flag = Column(SmallInteger, nullable=False, server_default='0', comment='0 待查看 1 已亮 2 未亮')
    company_uuid = Column(String(128), server_default='', comment='主体唯一标识')
    road_id = Column(Integer, nullable=False, server_default='0', comment='街道id')
    company_personal_flag = Column(SmallInteger, nullable=False, server_default='0', comment='主体类型标识0：全部  1：公司  2:个体工商户 3：个人')
    business_scope = Column(Text)
    authority = Column(String(255))
    shop_lat = Column(String(100))
    shop_lng = Column(String(100))
    service_tags = Column(String(255), comment='店铺服务标识')
    dead_check_flag = Column(SmallInteger, nullable=False, server_default='0', comment='死链扫描标识0：默认 1：扫描过')
    match_flag = Column(SmallInteger, nullable=False, server_default='0', comment='匹配标识')
    trade_flag = Column(SmallInteger, nullable=False, server_default='0', comment='交易标识')
    open_year = Column(SmallInteger, nullable=False, server_default='0', comment='开店年长')
    shop_uuid = Column(String(100), server_default='')
    collection_flag = Column(SmallInteger, server_default='0', comment='0 普通店铺  1 集合店铺')
    is_dead = Column(SmallInteger, nullable=False, server_default='0', comment='主库的死活标识')
    open_time = Column(String(64))
    labels_industry_name = Column(String(255), comment='产业标签名称 已英文逗号分割')
    labels_industry_id = Column(String(255), comment='产业标签id 已英文逗号分割')
    month_total_sold_num = Column(Integer, server_default='0')
    goods_static_status = Column(SmallInteger, nullable=False, server_default='0', comment='商品数统计状态')
    judge_content = Column(Text, comment='日常巡查数据')
    judge_content_flag = Column(SmallInteger, server_default='0', comment='是否更新了judge_content_flag')
    filing_status = Column(SmallInteger, nullable=False, server_default='1', comment='实地核查状态1：待实地人员确认 2：已确认待管理员审核3：审核通过4：审核不通过')
    field_check_user_id = Column(Integer, server_default='0', comment='实地核查人id')
    xinsi_flag = Column(SmallInteger, nullable=False, server_default='0', comment='主库是否存在标识 0:默认1:存在 2:不存在')
    judge_content_num = Column(Integer, server_default='11')
    light_flag = Column(Integer, server_default='1000', comment='1001亮照 1002亮承诺 2000 未亮 1000 待查看')
    illegal_flag = Column(SmallInteger, server_default='-1', comment='巡查类型  0暂无问题 1加入线索  2异常数据')
    judge_id = Column(Integer, server_default='0')
    live_user_id = Column(Integer)
    field_check_time = Column(TIMESTAMP)
    data_field_check_id = Column(Integer, server_default='0')
